# Unit and server testing workflow configuration for GHA.
# Author : Sameer Atre <SAtre@abacusbio.co.nz>

name: run-tests

on:
  push:
    branches:
      - testing
    paths:
      - '.github/workflows/tests.yml'
      - 'R/*'
      - 'tests/testthat/*'

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
      - uses: actions/checkout@v2
        with:
          install-r: true
          r-version: '4.0.2' 
      - run: Rscript -e 'print(R.version$version.string)'
      - name: Install packages
        run: Rscript -e "install.packages(c('testthat', 'tidyverse', 'here', 'shiny'))"
      - name: Run tests
        run: Rscript -e "source('tests/testthat.R')"
