# Shiny testing workflow configuration for GHA.
# Author : Sameer Atre <SAtre@abacusbio.co.nz>

name: run-shiny-tests

on:
  push:
    branches:
      - testing
    paths:
      - 'R/*'
      - 'R/tests/shinytest/*'
      - '.github/workflows/run-shiny-tests.yml'
      
jobs:
  run-shiny-tests:
    runs-on: windows-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
      - uses: actions/checkout@v2
      # - uses: r-lib/actions/setup-renv@v2
        with:
          install-r: true
          r-version: '4.0.2' 
      - run: Rscript -e 'print(R.version$version.string)'
      - name: Install packages
        # run: Rscript -e "install.packages(c('tidyverse', 'here', 'shinytest'))"
        run: Rscript -e "install.packages(c('shinyjs','tidyverse','here','shinytest','shiny','DT','shinyWidgets','reactable','dplyr','purrr','ggplot2','pheatmap','ggrepel','ggdendro','cluster','PMA','factoextra'))"
      - name: Install PhantomJS
        run: Rscript -e "shinytest::installDependencies()"
      - name: Run tests
        # run: Rscript -e "shinytest::testApp(appDir = './R',
        #                             quiet=TRUE, 
        #                             compareImages = FALSE, 
        #                             interactive = FALSE)"
        run: Rscript -e "shiny::runTests(appDir = './R')"
